name: jupyterlab-dat
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - bqplot
  - hvplot
  - ipywidgets
  - jsonpatch
  - jupyter-server-proxy
  - jupyterlab >=1.2.3,<1.3
  - nodejs >=11,<12
  - pandas
  - pillow
  - pip
  - python >=3.7,<3.8.0a0
  - qrcode
  - ujson
  - vdom
  - pip:
      - jupyter_bokeh
      - watchgod
