#!/usr/bin/env bash
set -eux
# do a dev install of the server side
python -m pip install -e . --ignore-installed --no-deps -vv
jupyter serverextension enable --sys-prefix --py jupyter_dat

# should have no extensions
jupyter labextension list

# do a dev build of the client side
jlpm bootstrap

# link all pieces to lab (no build)
jupyter labextension link $(cat labex.txt) --no-build

# should show need for a build
jupyter labextension list

# actually build
jupyter lab build && jupyter labextension list
